In [45]:
!pip install scikit-learn --upgrade

Requirement already up-to-date: scikit-learn in c:\users\ankita mishra\anaconda3\lib\site-packages (1.0.2)
Requirement already satisfied, skipping upgrade: joblib>=0.11 in c:\users\ankita mishra\anaconda3\lib\site-packages (from scikit-learn) (0.14.1)
Requirement already satisfied, skipping upgrade: scipy>=1.1.0 in c:\users\ankita mishra\anaconda3\lib\site-packages (from scikit-learn) (1.4.1)
Requirement already satisfied, skipping upgrade: numpy>=1.14.6 in c:\users\ankita mishra\anaconda3\lib\site-packages (from scikit-learn) (1.19.5)
Requirement already satisfied, skipping upgrade: threadpoolctl>=2.0.0 in c:\users\ankita mishra\anaconda3\lib\site-packages (from scikit-learn) (3.1.0)

In [46]:
# to save model, install joblib
!pip install joblib

Requirement already satisfied: joblib in c:\users\ankita mishra\anaconda3\lib\site-packages (0.14.1)

In [47]:
import pandas as pd

# Read CSV file and perform basic cleaning

In [76]:
df= pd.read_csv("exoplanet_dataset.csv")
# find out the type of each column and drop all objects and rowid and kepid
df.dtypes
df_update= df.drop(['rowid', 'kepid', 'kepoi_name', 
                    'kepler_name', 'koi_pdisposition', 'koi_score',
                    'koi_tce_delivname'], axis=1)
df_update= df_update.dropna(axis='columns', how='all')
df_update= df_update.dropna()
df_update.head()

,koi_disposition,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,CONFIRMED,0,0,0,0,9.488036,2.775000e-05,-2.775000e-05,170.538750,0.002160,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,CONFIRMED,0,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,FALSE POSITIVE,0,1,0,0,19.899140,1.494000e-05,-1.494000e-05,175.850252,0.000581,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,FALSE POSITIVE,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,CONFIRMED,0,0,0,0,2.525592,3.761000e-06,-3.761000e-06,171.595550,0.001130,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [79]:
y= df_update["koi_disposition"]
X= df_update.drop(columns= "koi_disposition")
# check if our selected feature has samples of atleast 2 classes
df_update.groupby('koi_disposition').count()

,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,koi_time0bk_err2,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
koi_disposition,,,,,,,,,,,,,,,,,,,,,
CANDIDATE,2114,2114,2114,2114,2114,2114,2114,2114,2114,2114,...,2114,2114,2114,2114,2114,2114,2114,2114,2114,2114
CONFIRMED,2272,2272,2272,2272,2272,2272,2272,2272,2272,2272,...,2272,2272,2272,2272,2272,2272,2272,2272,2272,2272
FALSE POSITIVE,4358,4358,4358,4358,4358,4358,4358,4358,4358,4358,...,4358,4358,4358,4358,4358,4358,4358,4358,4358,4358

# Create Train Test Split

In [80]:
from sklearn.model_selection import train_test_split

In [81]:
X_train, X_test, y_train, y_test= train_test_split(X, y, random_state=1, shuffle=True)

In [82]:
X_train.head()

,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,koi_time0bk_err2,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
6274,0,0,0,0,492.252990,0.011050,-0.011050,520.860000,0.01800,-0.01800,...,-152.0,4.478,0.055,-0.283,0.936,0.383,-0.089,292.13519,38.926491,13.465
3541,0,0,0,0,49.567408,0.000187,-0.000187,169.542270,0.00322,-0.00322,...,-111.0,4.474,0.059,-0.110,0.927,0.122,-0.066,290.67313,38.691010,13.597
8659,1,0,0,0,452.100930,0.054070,-0.054070,460.488400,0.05070,-0.05070,...,-214.0,4.456,0.066,-0.281,0.956,0.370,-0.103,292.10245,37.566910,15.107
4851,0,1,0,0,18.645329,0.000002,-0.000002,147.207512,0.00007,-0.00007,...,-175.0,4.554,0.038,-0.200,0.845,0.251,-0.079,287.63705,42.530819,15.511
1387,0,0,0,0,5.184990,0.000012,-0.000012,131.881400,0.00185,-0.00185,...,-131.0,4.680,0.059,-0.027,0.560,0.045,-0.056,295.90656,45.809120,14.744

# Pre-processing

In [83]:
# scale data using MinMaxScaler and perform feature selection
from sklearn.preprocessing import MinMaxScaler
X_scaler = MinMaxScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

# Train the Model

In [84]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter = 1000)
model.fit(X_train_scaled,y_train)

LogisticRegression(max_iter=1000)

In [85]:
print(f"Training Data Score: {model2.score(X_train_scaled, y_train)}")
print(f"Testing Data Score: {model2.score(X_test_scaled, y_test)}")

Training Data Score: 0.8601707837755413
Testing Data Score: 0.8563586459286368

# Hyperparameter Tuning

In [86]:
# using GridSearchCV to tune the model's parameters
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [1, 5, 10],
              'penalty': ["l1","l2"]}
model = LogisticRegression(solver = "liblinear")
grid = GridSearchCV(model, param_grid, verbose=3)

In [88]:
#Train model with grid search
grid.fit(X_train_scaled, y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits
[CV 1/5] END ...................C=1, penalty=l1;, score=0.864 total time=   0.7s
[CV 2/5] END ...................C=1, penalty=l1;, score=0.868 total time=   0.6s
[CV 3/5] END ...................C=1, penalty=l1;, score=0.882 total time=   0.5s
[CV 4/5] END ...................C=1, penalty=l1;, score=0.878 total time=   0.6s
[CV 5/5] END ...................C=1, penalty=l1;, score=0.879 total time=   0.6s
[CV 1/5] END ...................C=1, penalty=l2;, score=0.838 total time=   0.0s
[CV 2/5] END ...................C=1, penalty=l2;, score=0.835 total time=   0.0s
[CV 3/5] END ...................C=1, penalty=l2;, score=0.848 total time=   0.0s
[CV 4/5] END ...................C=1, penalty=l2;, score=0.869 total time=   0.0s
[CV 5/5] END ...................C=1, penalty=l2;, score=0.850 total time=   0.0s
[CV 1/5] END ...................C=5, penalty=l1;, score=0.867 total time=   2.4s
[CV 2/5] END ...................C=5, penalty=l1;, score=0.873 total time=   3.2s
[CV 3/5] END ...................C=5, penalty=l1;, score=0.889 total time=   1.2s
[CV 4/5] END ...................C=5, penalty=l1;, score=0.888 total time=   2.5s
[CV 5/5] END ...................C=5, penalty=l1;, score=0.883 total time=   1.9s
[CV 1/5] END ...................C=5, penalty=l2;, score=0.851 total time=   0.0s
[CV 2/5] END ...................C=5, penalty=l2;, score=0.851 total time=   0.0s
[CV 3/5] END ...................C=5, penalty=l2;, score=0.877 total time=   0.0s
[CV 4/5] END ...................C=5, penalty=l2;, score=0.879 total time=   0.0s
[CV 5/5] END ...................C=5, penalty=l2;, score=0.863 total time=   0.0s
[CV 1/5] END ..................C=10, penalty=l1;, score=0.869 total time=   2.4s
[CV 2/5] END ..................C=10, penalty=l1;, score=0.877 total time=   3.1s
[CV 3/5] END ..................C=10, penalty=l1;, score=0.890 total time=   2.6s
[CV 4/5] END ..................C=10, penalty=l1;, score=0.888 total time=   3.5s
[CV 5/5] END ..................C=10, penalty=l1;, score=0.883 total time=   3.7s
[CV 1/5] END ..................C=10, penalty=l2;, score=0.860 total time=   0.0s
[CV 2/5] END ..................C=10, penalty=l2;, score=0.858 total time=   0.1s
[CV 3/5] END ..................C=10, penalty=l2;, score=0.880 total time=   0.2s
[CV 4/5] END ..................C=10, penalty=l2;, score=0.881 total time=   0.1s
[CV 5/5] END ..................C=10, penalty=l2;, score=0.870 total time=   0.0s

GridSearchCV(estimator=LogisticRegression(solver='liblinear'),
             param_grid={'C': [1, 5, 10], 'penalty': ['l1', 'l2']}, verbose=3)

In [89]:
print(grid.best_params_)
print(grid.best_score_)

{'C': 10, 'penalty': 'l1'}
0.8815199949768375

# Save the Model

In [90]:
import joblib
filename = 'LogisticRegression_Model1.sav'
joblib.dump(grid, filename)

['LogisticRegression_Model1.sav']